# Generated by Django 5.2 on 2025-04-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='position',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Supervisor', 'Supervisor'), ('Logistica', 'Logistica'), ('Inventario', 'Inventario')], max_length=15),
        ),
    ]
