# Generated by Django 5.2 on 2025-05-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('add', 'Agregó'), ('edit', 'Editó'), ('delete', 'Eliminó'), ('login', 'Inició sesión'), ('logout', 'Cerró sesión'), ('add_producto', 'Agregó Producto'), ('edit_producto', 'Editó Producto'), ('delete_producto', 'Eliminó Producto'), ('add_proveedor', 'Agregó Proveedor'), ('edit_proveedor', 'Editó Proveedor'), ('delete_proveedor', 'Eliminó Proveedor'), ('add_venta', 'Agregó Venta'), ('edit_venta', 'Editó Venta'), ('delete_venta', 'Eliminó Venta')], max_length=20),
        ),
    ]
