# Generated by Django 5.2 on 2025-05-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('add', 'Agregó'), ('edit', 'Editó'), ('delete', 'Eliminó'), ('login', 'Login'), ('logout', 'Logout'), ('add_producto', 'Agregó un producto'), ('edit_producto', 'Editó un producto'), ('delete_producto', 'Eliminó un producto'), ('add_proveedor', 'Agregó un proveedor'), ('edit_proveedor', 'Editó un proveedor'), ('delete_proveedor', 'Eliminó un proveedor'), ('add_venta', 'Agregó una venta'), ('edit_venta', 'Editó una venta'), ('delete_venta', 'Eliminó una venta')], max_length=20),
        ),
    ]
