# Generated by Django 5.2 on 2025-05-26 09:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_producto_proveedor_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venta', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_envio', models.CharField(choices=[('proceso', 'En Proceso'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=10)),
                ('region', models.CharField(choices=[('arica_parinacota', 'Región de Arica y Parinacota'), ('tarapaca', 'Región de Tarapacá'), ('antofagasta', 'Región de Antofagasta'), ('atacama', 'Región de Atacama'), ('coquimbo', 'Región de Coquimbo'), ('valparaiso', 'Región de Valparaíso'), ('metropolitana', 'Región Metropolitana'), ('ohiggins', 'Región de O’Higgins'), ('maule', 'Región del Maule'), ('nuble', 'Región del Ñuble'), ('biobio', 'Región de Biobío'), ('araucania', 'Región de La Araucanía'), ('rios', 'Región de Los Ríos'), ('lagos', 'Región de Los Lagos'), ('aysen', 'Región de Aysén'), ('magallanes', 'Región de Magallanes')], max_length=30, verbose_name='Región')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('id_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto', verbose_name='ID del Pedido')),
                ('talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.productotalla', verbose_name='Talla')),
            ],
        ),
    ]
