# Generated by Django 5.2 on 2025-05-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_envio', models.CharField(choices=[('proceso', 'En Proceso'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=10)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
