# Generated by Django 5.2 on 2025-05-26 04:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='email',
            field=models.EmailField(default='sin_direccion', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='id_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto', verbose_name='ID del Pedido'),
        ),
        migrations.AddField(
            model_name='venta',
            name='region',
            field=models.CharField(choices=[('arica_parinacota', 'Región de Arica y Parinacota'), ('tarapaca', 'Región de Tarapacá'), ('antofagasta', 'Región de Antofagasta'), ('atacama', 'Región de Atacama'), ('coquimbo', 'Región de Coquimbo'), ('valparaiso', 'Región de Valparaíso'), ('metropolitana', 'Región Metropolitana'), ('ohiggins', 'Región de O’Higgins'), ('maule', 'Región del Maule'), ('nuble', 'Región del Ñuble'), ('biobio', 'Región de Biobío'), ('araucania', 'Región de La Araucanía'), ('rios', 'Región de Los Ríos'), ('lagos', 'Región de Los Lagos'), ('aysen', 'Región de Aysén'), ('magallanes', 'Región de Magallanes')], default='sin_direccion', max_length=30, verbose_name='Región'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.productotalla', verbose_name='Talla'),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono',
            field=models.CharField(default='sin_telefono', max_length=20, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
