# Generated by Django 5.2 on 2025-05-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_pedido',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='ID del Pedido'),
        ),
    ]
