# Generated by Django 5.2 on 2025-05-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_direccion_venta_email_venta_id_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_venta',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
