# Generated by Django 5.2 on 2025-05-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_id_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id_pedido',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='ID del Pedido'),
            preserve_default=False,
        ),
    ]
