# Generated by Django 5.2 on 2025-05-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_id_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id_pedido',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='ID del Pedido'),
        ),
    ]
