# Generated by Django 5.2 on 2025-05-23 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '__first__'),
        ('ventas', '0004_alter_venta_id_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto', verbose_name='ID del Pedido'),
        ),
    ]
