# Generated by Django 5.2 on 2025-05-23 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '__first__'),
        ('ventas', '0005_alter_venta_id_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.productotalla', verbose_name='Talla'),
        ),
    ]
