# Generated by Django 5.2 on 2025-05-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_venta_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='numero_casa',
        ),
        migrations.AlterField(
            model_name='venta',
            name='region',
            field=models.CharField(choices=[('arica_parinacota', 'Región de Arica y Parinacota'), ('tarapaca', 'Región de Tarapacá'), ('antofagasta', 'Región de Antofagasta'), ('atacama', 'Región de Atacama'), ('coquimbo', 'Región de Coquimbo'), ('valparaiso', 'Región de Valparaíso'), ('metropolitana', 'Región Metropolitana'), ('ohiggins', 'Región de O’Higgins'), ('maule', 'Región del Maule'), ('nuble', 'Región del Ñuble'), ('biobio', 'Región de Biobío'), ('araucania', 'Región de La Araucanía'), ('rios', 'Región de Los Ríos'), ('lagos', 'Región de Los Lagos'), ('aysen', 'Región de Aysén'), ('magallanes', 'Región de Magallanes')], max_length=30, verbose_name='Región'),
        ),
    ]
