# Generated by Django 5.2 on 2025-05-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('marcas_principales', models.CharField(blank=True, max_length=50, null=True)),
                ('metodo_pago', models.CharField(max_length=10)),
                ('tiempo_envio', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
