# Generated by Django 5.2 on 2025-05-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='page_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
