# Generated by Django 5.2 on 2025-05-24 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_image_url_proveedor_page_url'),
        ('proveedores', '0003_proveedor_descripcion'),
    ]

    operations = [
    ]
