# Generated by Django 5.2 on 2025-05-24 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_merge_20250523_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='image_url',
            new_name='url_imagen',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='page_url',
            new_name='url_pagina',
        ),
    ]
