# Generated by Django 5.2 on 2025-05-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('numero_orden', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_producto_unidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('talla', models.CharField(max_length=10)),
                ('numero_tracking', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boleta_factura', models.FileField(blank=True, null=True, upload_to='boletas_facturas/')),
            ],
        ),
    ]
