# Generated by Django 5.2 on 2025-05-26 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('proveedores', '0005_rename_image_url_proveedor_url_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='proveedores.proveedor'),
        ),
    ]
