# Generated by Django 5.2 on 2025-04-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_boleta_factura_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
    ]
