# Generated by Django 5.2 on 2025-05-26 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_proveedor_fk_data_migration'),
        ('proveedores', '0005_rename_image_url_proveedor_url_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='proveedores.proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
