# Generated by Django 5.2 on 2025-05-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
